### ISSUE TITLE
Scatter Login gives error "Unhandled Rejection (TypeError): Cannot read property 'send' of null"

### ISSUE THREAD

**Issue by delans** [rudijs/eos-scatter-desktop-dapp-seed#1]
Hi Rudijs,

I downloaded the project, installed the packages (npm install) and started the app (npm start). 

Then I see the app, but I can't get Scatter to work. After clicking on Login I see:
![image](https://user-images.githubusercontent.com/281921/48298688-00b7d180-e4f4-11e8-8ee6-1ff8d9e794dc.png)

Context: 
- I updated the config.js to the public chain (via api.eosnewyork.io:443 endpoint)
- In BlockchainInfo.js I updated the endpoint tot api.eosnewyork.io:433 too, which works fine as I see the mainnet endpoint data in the app

Hope you can help me out. Getting Scatter to work in ReactJS serves me a headache at the moment :)

Keep up your good work!

**Comment by rudijs** [comment]
Oh .. I'm surprised anyone found this and tried to use it :-)

I have two old repos and am moving them into one new one.

With create-react-app v2 there is typescript support - so you may or may not like to hear my current work in is typescript.

It's another repo, for now if you like checkout:

1. Backend - the docs/ folder here for EOSIO docker setup: https://github.com/rudijs/eos-block-explorer/blob/master/docs/create_blockchain.md
2. Frontend - https://github.com/rudijs/eos-explorer

I'm just hacking around with it so the docs are lacking, and I haven't really prepared it for public release.

FYI you can take the typescript version but just write regular javascript if you're not into typesecript.

**Comment by delans** [comment]
Thanks you so much for your quick response and sorry for finding the repo ;-). 

I get the same error on the https://github.com/rudijs/eos-explorer repo:
![image](https://user-images.githubusercontent.com/281921/48300775-c828ef80-e515-11e8-9c54-3e525d4f2146.png)

I'm not too familiar with TypeScript but it is installed globally on my Mac.

Any thoughts maybe :)?

Thanks so far!!

**Comment by rudijs** [comment]
Hmm .. it works for me.

What version of Scatter are you using?

I have v9.6.0

Also I'm on node v10.12.0

**Comment by delans** [comment]
That did the trick. Was working with the most recent version of the Chrome Extension. 
Downloading and installing the Desktop version did the trick. 

Thank you SO much for your time!
